trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '673b47f8-27fd-488b-a6d9-696a8f85aaf9'
  imageRepository: 'webapp'
  containerRegistry: 'acrcontainerdeploy.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'
  appName: 'WebAppOneContainerDeploy'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImageName: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy a container
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'DevSchoolING (5334c216-94db-441b-b614-2e0c708e2b87)'
        appName: $(appName)
        imageName: $(containerRegistry)/$(imageRepository):$(tag)
- stage: Test
  displayName: 'Test API with curl'
  dependsOn: Deploy
  jobs:
  - job: test
    displayName: 'Test API'
    steps:
    - script: |
        curl https://webapponecontainerdeploy.azurewebsites.net/check_api
      displayName: 'Send API test request'
    - script: |
        if [ "$?" -eq 0 ]
        then
          echo "API test succeeded"
          exit 0
        else
          echo "API test failed"
          exit 1
        fi
      displayName: 'Check API test response'