trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    Dockerfile: $(Build.SourcesDirectory)/Dockerfile
    tags: |
      $(Build.Repository.Name):$(Build.SourceVersion)
      $(Build.Repository.Name):latest

- task: Docker@2
  displayName: Push Docker image to registry
  inputs:
    command: push
    containerRegistry: 'myregistry'
    repository: $(Build.Repository.Name)
    tags: |
      $(Build.Repository.Name):$(Build.SourceVersion)
      $(Build.Repository.Name):latest