trigger:
- main

variables:
  dockerHubConnection: 'dockerhub'
  dockerHubUsername: 'mirelstancu99'
  dockerHubPassword: 'Myrel112@@'
  imageRepository: 'mirelstancu99/devschoolproject'
  containerRegistry: $(dockerHubConnection)
  imageTag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Deploy image to Azure Web App
  inputs:
    containerRegistryType: 'Container Registry'
    dockerRegistryEndpointConnection: $(dockerHubConnection)
    dockerImageName: $(containerRegistry)/$(imageRepository):$(imageTag)
    appType: 'webAppLinux'
    appName: 'my-flask-app'
    deploymentMethod: 'containerRegistry'
  env:
    DOCKERHUB_USERNAME: $(dockerHubUsername)
    DOCKERHUB_PASSWORD: $(dockerHubPassword)
