---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: devschoolproject.azurecr.io/webapp
          ports:
          - containerPort: 5000
            protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: webapp-pv
      volumes:
          - name: webapp-pv
            persistentVolumeClaim:
              claimName: webapp-pvc