apiVersion : apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: devschoolproject.azurecr.io/webapp
          ports:
          - containerPort: 5000
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 750Mi