apiVersion : apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: devschoolproject.azurecr.io/webapp
          ports:
          - containerPort: 5000
            protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
          - name: data-volume
            mountPath: /webapp/database.db
            subPath: database.db
      volumes:
        - name: data-volume
          hostPath:
            path: /app/database.db