apiVersion : apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: luiciudin/ing-app:latest
          ports:
          - containerPort: 5000
            protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 750Mi